version: "3.8"

services:
  api:
    build: .
    container_name: primemotors-api
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./database.sqlite:/app/database.sqlite
