services:
  api:
    build: .
    container_name: primemotors-api
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - primemotors_db:/app/db
      - ./src:/app/src  # hot reload
volumes:
  primemotors_db: